<?php if ($block->getContainers()) : ?>
    <?php $containers = $block->getContainers(); ?>
    <div class="store-switcher store-view">
        <span class="store-switcher-label"><?php /* @escapeNotVerified */ echo __('View:') ?></span>
        <div class="actions dropdown closable">
            <input type="hidden" name="container_switcher" id="container_switcher"
                   data-role="container-id" data-param="<?php /* @escapeNotVerified */ echo $block->getContainerVarName() ?>"
                   value="<?php echo $block->escapeHtml($block->getWebsiteId()) ?>"
                   onchange="switchScope(this);"<?php /* @escapeNotVerified */ echo $block->getUiId()?> />
            <input type="hidden" name="store_switcher" id="store_switcher"
                   data-role="store-view-id" data-param="<?php /* @escapeNotVerified */ echo $block->getStoreVarName() ?>"
                   value="<?php echo $block->escapeHtml($block->getStoreId()) ?>"
                   onchange="switchScope(this);"<?php /* @escapeNotVerified */ echo $block->getUiId()?> />
            <button
                type="button"
                class="admin__action-dropdown"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                aria-haspopup="true"
                id="store-change-button">
                <?php /* @escapeNotVerified */ echo $block->getCurrentSelectionName() ?>
            </button>
            <ul class="dropdown-menu" data-role="stores-list">
                <?php if ($block->hasDefaultOption()): ?>
                    <li class="store-switcher-all <?php if ( ! ($block->getDefaultSelectionName() != $block->getCurrentSelectionName())) {
                        echo "disabled";
                    } ?> <?php if ( ! $block->hasScopeSelected()) {
                        ?> current<?php
                    } ?>">
                        <?php if ($block->getDefaultSelectionName() != $block->getCurrentSelectionName()) {
                            ?>
                            <a data-role="store-view-id" data-value="" href="#">
                                <?php /* @escapeNotVerified */ echo $block->getDefaultSelectionName() ?>
                            </a>
                            <?php
                        } else {
                            ?>
                            <span><?php /* @escapeNotVerified */ echo $block->getDefaultSelectionName() ?></span>
                            <?php
                        } ?>
                    </li>
                <?php endif; ?>
                <?php foreach ($containers as $container) : ?>
                    <?php $showContainer = false; ?>
                    <?php foreach ($block->getStores() as $store) : ?>
                        <?php if ($showContainer == false) : ?>
                            <?php $showContainer = true; ?>
                            <li class="store-switcher-container <?php if ( ! ($block->isContainerSwitchEnabled() && ! $block->isContainerSelected($container))) {
                                echo "disabled";
                            } ?> <?php if ($block->isContainerSelected($container)) {
                                ?> current<?php
                            } ?>">
                                <?php if ($block->isContainerSwitchEnabled() && ! $block->isContainerSelected($container)) {
                                    ?>
                                    <a data-role="container-id" data-value="<?php echo $block->escapeHtml($block->getContainerName($container)) ?>" href="#">
                                        <?php echo $block->escapeHtml($block->getContainerLabel($container)) ?>
                                    </a>
                                    <?php
                                } else {
                                    ?>
                                    <span><?php echo $block->escapeHtml($block->getContainerLabel($container)) ?></span>
                                    <?php
                                } ?>
                            </li>
                        <?php endif; ?>

                        <?php $isDisabled = (
                            !$block->isStoreSwitchEnabled()
                            && ($block->isStoreSelected($store) && $block->isContainerSelected($container))
                        );
                        ?>

                        <li class="store-switcher-store-view <?php if ($isDisabled) {
                            echo "disabled";
                        } ?> <?php if ($block->isStoreSelected($store) && $block->isContainerSelected($container)) {
                            ?> current<?php
                        } ?>">
                            <?php if ($block->isStoreSwitchEnabled() && ! ($block->isStoreSelected($store) && $block->isContainerSelected($container))) {
                                ?>
                                <a data-role="store-view-id" data-value="<?php echo $block->escapeHtml($store->getId()) ?>" data-container="<?php echo $block->escapeHtml($block->getContainerName($container)) ?>" href="#">
                                    <?php echo $block->escapeHtml($store->getName()) ?>
                                </a>
                                <?php
                            } else {
                                ?>
                                <span><?php echo $block->escapeHtml($store->getName()) ?></span>
                                <?php
                            } ?>
                        </li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
                <?php if ($block->getShowManageStoresLink() && $block->getAuthorization()->isAllowed('Magento_Backend::store')): ?>
                    <li class="dropdown-toolbar">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getUrl('*/system_store') ?>"><?php /* @escapeNotVerified */ echo __('Stores Configuration') ?></a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        <?php echo $block->getHintHtml() ?>
    </div>

    <script>
        require([
            'jquery',
            'Magento_Ui/js/modal/confirm'
        ], function(jQuery, confirm){

            (function($) {
                var $storesList = $('[data-role=stores-list]');
                $storesList.on('click', '[data-value]', function(event) {
                    var val = $(event.target).data('value');
                    var role = $(event.target).data('role');
                    var container = $(event.target).data('container');
                    var switcher = $('[data-role='+role+']');

                    event.preventDefault();

                    if (((typeof container) != 'undefined') && (container != ""))  {
                        switcher.switchParams = 'container/' + container + '/';
                        switcher.data("switch-params", 'container/' + container + '/');
                        var containerSwitcher = $('[data-role=container]');
                    }

                    if (((typeof containerSwitcher) != 'undefined'))  {
                        if (!containerSwitcher.val() || container != containerSwitcher.val()) {
                            switcher.val(val).trigger('change'); // Set the value & trigger event
                        }
                    } else if (!switcher.val() || val != switcher.val()) {
                        switcher.val(val).trigger('change'); // Set the value & trigger event
                    }

                });
            })(jQuery);

            var scopeSwitcherHandler;

            function switchScope(obj) {
                var switcher = jQuery(obj);
                var scopeId = switcher.val();
                var scopeParams = '';
                if (scopeId) {
                    scopeParams = switcher.data('param') + '/' + scopeId + '/';
                }

                if (obj.switchParams) {
                    scopeParams += obj.switchParams;
                }

                if (switcher.data('switch-params')) {
                    scopeParams += switcher.data('switch-params');
                }

                if ((typeof scopeSwitcherHandler) != 'undefined') {
                    var switcherParams = {
                        scopeId: scopeId,
                        scopeParams: scopeParams,
                        useConfirm: <?php echo (int)$block->getUseConfirm() ?>
                    };
                    scopeSwitcherHandler(switcherParams);
                } else {

                    <?php if ($block->getUseConfirm()): ?>

                    confirm({
                        content:  "<?php /* @escapeNotVerified */ echo __('Please confirm scope switching. All data that hasn\'t been saved will be lost.') ?>",
                        actions: {
                            confirm: function() {
                                reload();
                            },
                            cancel: function() {
                                obj.value = '<?php echo $block->escapeHtml($block->getStoreId()) ?>';
                            }
                        }
                    });

                    <?php else: ?>
                    reload();
                    <?php endif; ?>
                }

                function reload() {
                    <?php if (!$block->isUsingIframe()): ?>
                    var url = '<?php /* @escapeNotVerified */ echo $block->getSwitchUrl() ?>' + scopeParams;
                    setLocation(url);
                    <?php else: ?>
                    jQuery('#preview_selected_store').val(scopeId);
                    jQuery('#preview_form').submit();

                    jQuery('.store-switcher .dropdown-menu li a').each(function() {
                        var $this = jQuery(this);

                        if ($this.data('role') === 'store-view-id' && $this.data('value') == scopeId) {
                            jQuery('#store-change-button').html($this.text());
                        }
                    });

                    jQuery('#store-change-button').click();
                    <?php endif; ?>
                }
            }

            window.scopeSwitcherHandler = scopeSwitcherHandler;
            window.switchScope = switchScope;

        });
    </script>
<?php endif; ?>
