name: Remove safe to test label

on:
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write

jobs:
  remove-label:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: 'safe to test',
            })
